#!/usr/bin/env python

import sys
import re

DATE_CLEAN_REGEX = re.compile(r"\$Date:[0-9: +\-]+\$")
DATE_CLEAN_REPLACE = "$Date$"
AUTHOR_CLEAN_REGEX = re.compile(r"\$Author:[^$]+\$")
AUTHOR_CLEAN_REPLACE = "$Author$"
REVISION_CLEAN_REGEX = re.compile(r"\$Revision:[0-9a-z]+\$")
REVISION_CLEAN_REPLACE = "$Revision$"
FILE_CLEAN_REGEX = re.compile(r"\$File:[^$]*\$")
FILE_CLEAN_REPLACE = "$File$"

def _error(msg):
    sys.stderr.write(msg)
    sys.stderr.flush()
    sys.exit(1)

def clean():
  for line in sys.stdin:
    if DATE_CLEAN_REGEX.search(line):
        line = DATE_CLEAN_REGEX.sub(DATE_CLEAN_REPLACE, line)
    if AUTHOR_CLEAN_REGEX.search(line):
        line = AUTHOR_CLEAN_REGEX.sub(AUTHOR_CLEAN_REPLACE, line)
    if REVISION_CLEAN_REGEX.search(line):
        line = REVISION_CLEAN_REGEX.sub(REVISION_CLEAN_REPLACE, line)
    sys.stdout.write(line)

if __name__ == '__main__':
  clean()
