-- COMMITHASH : <COMMITHASH>
-- COMMITHASHABBREVIATED : <COMMITHASHABBREVIATED>
-- TREEHASH : <TREEHASH>
-- TREEHASHABBREVIATED : <TREEHASHABBREVIATED>
-- PARENTHASHES : <PARENTHASHES>
-- PARENTHASHESABBREVIATED : <PARENTHASHESABBREVIATED>
-- AUTHORNAME : <AUTHORNAME>
-- AUTHORNAMEMAILCAP : <AUTHORNAMEMAILCAP>
-- AUTHOREMAIL : <AUTHOREMAIL>
-- AUTHOREMAILMAILCAP : <AUTHOREMAILMAILCAP>
-- AUTHORDATE : <AUTHORDATE>
-- AUTHORDATERFC2822 : <AUTHORDATERFC2822>
-- AUTHORDATERELATIVE : <AUTHORDATERELATIVE>
-- AUTHORDATEUNIX : <AUTHORDATEUNIX>
-- AUTHORDATEISO8601 : <AUTHORDATEISO8601>
-- COMMITTERNAME : <COMMITTERNAME>
-- COMMITTERNAMEMAILCAP : <COMMITTERNAMEMAILCAP>
-- COMMITTERDATE : <COMMITTERDATE>
-- COMMITTERDATERFC2822 : <COMMITTERDATERFC2822>
-- COMMITTERDATERELATIVE : <COMMITTERDATERELATIVE>
-- COMMITTERDATEUNIX : <COMMITTERDATEUNIX>
-- COMMITTERDATEISO8601 : <COMMITTERDATEISO8601>
-- REFNAMES : <REFNAMES>
-- ENCODING : <ENCODING>
-- SUBJECT : <SUBJECT>
-- SUBJECTSANITIZED : <SUBJECTSANITIZED>
-- REFLOGSELECTOR : <REFLOGSELECTOR>
-- REFLOGSELECTORSHORT : <REFLOGSELECTORSHORT>
-- REFLOGIDENTITYNAME : <REFLOGIDENTITYNAME>
-- REFLOGIDENTITYNAMEMAILCAP : <REFLOGIDENTITYNAMEMAILCAP>
-- REFLOGIDENTITYEMAIL : <REFLOGIDENTITYEMAIL>
-- REFLOGIDENTITYEMAILMAILCAP : <REFLOGIDENTITYEMAILMAILCAP>
-- REFLOGSUBJECTS : <REFLOGSUBJECTS>
-- BRANCH: <BRANCH>
-- FILE: <FILE>
-- FILENAME: <FILENAME>
-- <CHANGELOG:--reverse:3:%an : %ai : %s>

SELECT * FROM TEST;
SELECT * FROM DUAL;
SELECT * FROM TEST;
SELECT * FROM DUAL;
SELECT * FROM TEST;
